import type { DocItem } from "./types"

export const mockDocuments: DocItem[] = [
  {
    id: "CERT-2024-0001",
    title: "Completion Certificate - MongoDB Online Training",
    issuer: "tutorialspoint",
    issueDate: "2024-01-01",
    type: "issued",
    category: "Education",
    tags: ["certificate", "education", "mongodb"],
  },
  {
    id: "CERT-2024-0002",
    title: "Identity Proof - PAN Card",
    issuer: "Income Tax Department, Govt. of India",
    issueDate: "2023-04-01",
    type: "uploaded",
    category: "Identity",
    tags: ["KYC", "identity", "tax"],
  },
  {
    id: "CERT-2024-0003",
    title: "COVID-19 Vaccination Certificate",
    issuer: "Ministry of Health & Family Welfare",
    issueDate: "2021-10-23",
    type: "issued",
    category: "Health",
    tags: ["health", "covid19", "vaccination"],
  },
  {
    id: "CERT-2025-0107",
    title: "Course Certificate - Data Structures & Algorithms",
    issuer: "NPTEL - IIT Madras",
    issueDate: "2025-02-15",
    type: "issued",
    category: "Education",
    tags: ["certificate", "computer science", "NPTEL"],
  },
  {
    id: "CERT-2024-0005",
    title: "Driving License",
    issuer: "Regional Transport Office, Delhi",
    issueDate: "2022-06-12",
    type: "uploaded",
    category: "Identity",
    tags: ["license", "transport", "identity"],
  },
  {
    id: "CERT-2024-0006",
    title: "Aadhaar Card",
    issuer: "UIDAI",
    issueDate: "2019-03-15",
    type: "issued",
    category: "Identity",
    tags: ["identity", "aadhaar", "government"],
  },
  {
    id: "CERT-2024-0007",
    title: "B.Tech Degree Certificate",
    issuer: "Delhi Technological University",
    issueDate: "2023-07-20",
    type: "issued",
    category: "Education",
    tags: ["degree", "engineering", "university"],
  },
]
