import { Geist, Geist_Mono } from "next/font/google";
import { NavbarDemo } from "@/components/NavbarContent";
import { ThirdwebProvider } from "thirdweb/react";
import { client } from "../lib/client";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      <ThirdwebProvider client={client}>
        <NavbarDemo />
        {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
